package com.gradualgames.ggvm;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

/**
 * Created by derek on 5/23/2017.
 *
 * This can be used to replace locations on a bus's memory map with a no-op. This
 * can be used prior to installing a bus event generator for a virtual hardware
 * register, so gratuitous warnings are not generated by ReadWriteRangeWarning.
 */
public class ReadWriteRangeNop implements ReadWriteRange {
    @Override
    public byte read(int address) {
        return 0;
    }

    @Override
    public void write(int address, byte value) {

    }

    @Override
    public int lower() {
        return 0;
    }

    @Override
    public int upper() {
        return 0;
    }

    @Override
    public void save(OutputStream outputStream) throws IOException {

    }

    @Override
    public void load(InputStream inputStream) throws IOException {

    }
}
